// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADTUbVD8Wv_Zt7Q5oob9OwN-zWoL0uJP8',
    appId: '1:635058857239:web:d2e9576868a414d1744352',
    messagingSenderId: '635058857239',
    projectId: 'batchmanager-a04ca',
    authDomain: 'batchmanager-a04ca.firebaseapp.com',
    storageBucket: 'batchmanager-a04ca.appspot.com',
    measurementId: 'G-H2FGWMMEM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpyzY8fYacD5PyaTbXSLSftObIjG13Mhk',
    appId: '1:635058857239:android:2caa8e96921eb483744352',
    messagingSenderId: '635058857239',
    projectId: 'batchmanager-a04ca',
    storageBucket: 'batchmanager-a04ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOVbSRU33o4XFsVRaQ6ZGVgOcbhw_HM_k',
    appId: '1:635058857239:ios:4a3410f8de4559a3744352',
    messagingSenderId: '635058857239',
    projectId: 'batchmanager-a04ca',
    storageBucket: 'batchmanager-a04ca.appspot.com',
    iosClientId: '635058857239-b2f8t4pl98v8d5cdnm9ssglru291u5ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.batchManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOVbSRU33o4XFsVRaQ6ZGVgOcbhw_HM_k',
    appId: '1:635058857239:ios:4a3410f8de4559a3744352',
    messagingSenderId: '635058857239',
    projectId: 'batchmanager-a04ca',
    storageBucket: 'batchmanager-a04ca.appspot.com',
    iosClientId: '635058857239-b2f8t4pl98v8d5cdnm9ssglru291u5ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.batchManager',
  );
}
